### ISSUE TITLE
[feature] ability to work with Angular Universal

### ISSUE THREAD

**Issue by MarkPieszak** [500tech/angular-tree-component#152]
At the moment if you attempt to add the library to an application using Universal, you'll get :

    Exception: Call to Node module failed with error: ReferenceError: Element is not defined

seen here (https://github.com/MarkPieszak/aspnetcore-angular2-universal/issues/44)

ng2-bootstrap faced similar hurdles when making their library universal, it looks like they can be fixed with some TS work-arounds potentially. https://github.com/valor-software/ng2-bootstrap/issues/964

Here's one check in that fixed similar issues.
https://github.com/valor-software/ng2-bootstrap/commit/d20ccf109c9a718823b2eab4f971b3595b04a83f

Just wanted to get it out there!

A good article here on deploying libraries to keep them usable outside of the browser platform as well.  http://blog.mgechev.com/2017/01/21/distributing-an-angular-library-aot-ngc-types/

**Comment by nxplus** [comment]
Did not realize the error had anything to do with universal, thank you for making this clear.
So there isn't any specific fixes suggested yet?

**Comment by MarkPieszak** [comment]
I'm not aware of anything to fix it just yet, the library itself is accessing the NativeElement and such (which I believe is where the errors are stemming from).  A few things would have to be updated/changed here to let the library be used in Webworkers / Server / etc.

**Comment by adamkleingit** [comment]
Will fix today. Thanks!

**Comment by adamkleingit** [comment]
Fixed in 2.8.0.
Please verify

**Comment by nxplus** [comment]
This is great news.
However I tried 2.8.0 (with universal) and this is showing up in the console:

```
An unhandled exception has occurred: Call to Node module failed with error: ...\node_modules\angular2-tree-component\dist\angular2-tree-component.js:10
import { NgModule } from '@angular/core';
^^^^^^
SyntaxError: Unexpected token import
```

**Comment by adamkleingit** [comment]
It looks like you're trying to use the component without bundling it with something like webpack.
Can you share link to your code?

**Comment by nxplus** [comment]
It is bundled into my vendor.js with webpack like this:
(I can see it gets appended to the bottom of the file)
```
    entry: {
        vendor: [
            ....
            'angular2-tree-component'        <-- I assume this is correct
```

This is just tested in a larger project of mine, I might be able to set up a smaller test project and share the code.

**Comment by nxplus** [comment]
I have created an asp.net test project, it is based on the "asp.net core angular 2 starter application" template. I still have the same error.

The component is loaded into the Dashboard component
[](https://bitbucket.org/nclick/ng2universalwebpackng2treecomp)

**Comment by MarkPieszak** [comment]
@Moalpima did you want to try re-testing it out? I think I remember you were running into this issue with the Component.

Thank you @adamkleingit ! :100: :+1:

**Comment by jycouet** [comment]
Hi, 

I also have this error:
```
import { NgModule } from '@angular/core';
SyntaxError: Unexpected token import
```

I'm on an angular2-meteor app. 
Is it corrected on your side @nxplus ?

Thx

**Comment by MarkPieszak** [comment]
Unexpected token import is coming from typescript not being transpiled, make sure you have the appropriate loaders in webpack or whatever you're using to set TS up.

**Comment by jycouet** [comment]
Sorry, I don't figure out what is wrong on my side.

I see that the content angular2-tree-component is bundled in my output js file... but I still have this error **Unexpected token import**:
![image](https://cloud.githubusercontent.com/assets/5312607/22671333/1c73a112-ecce-11e6-8ea5-f77d8829e74f.png)

Can it be my tsconfig.json?
```
{
  "compilerOptions": {
    "target": "es6",
    "lib": [
      "es6",
      "dom"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "sourceMap": true,
    "types": ["meteor-typings"]
  },
  "compileOnSave": false,
  "angularCompilerOptions": {
    "genDir": "aot",
    "skipMetadataEmit": true
  }
}
```

Thank you for your help

**Comment by MarkPieszak** [comment]
you have an es6 target, try es5?

**Comment by jycouet** [comment]
Yes I did, event with target es5 I have the same thing.

**Comment by nxplus** [comment]
@jycouet still same error, my example is taken directly from the visual studio angular 2 template here: 
https://marketplace.visualstudio.com/items?itemName=MadsKristensen.ASPNETCoreTemplatePack

As of now I really have no clue where to look. I also tried changing some tsconfig settings without luck.

**Comment by adamkleingit** [comment]
I'm guessing this is a webpack config issue?
Maybe this line:
```
    externals: [nodeExternals({ whitelist: [allFilenamesExceptJavaScript] })] // Don't bundle .js files from node_modules
```

**Comment by Soarc** [comment]
Hi. I'm using Tree component 2.8.1 with angular-universal and getting following error:
`Exception: Call to Node module failed with error: Prerendering failed because of error: ReferenceError: Element is not defined`

I little digging shows, that problem is not showing up, if i comment out "import './vendor/closest';" row in polyfills.js. Is there any workaround for this?

**Comment by nxplus** [comment]
@adamkleingit that seems very likely, thank you for taking your time.
Perhaps this is also the reason why I have had trouble with some other components that are using multiple js files.

I tried "whitelist: ['angular2-tree-component']" but it didn't seem to work, will investigate further.

**Comment by adamkleingit** [comment]
Right.
I'll need to reimplement `closest` using Angular `renderer`

**Comment by Soarc** [comment]
I'll fork then and try to implement using Angular renderer, because i need it now. Will create pull request, if it be actual at that moment.

**Comment by adamkleingit** [comment]
@Soarc  Thanks I would really appreciate the help

**Comment by IgorMoreira** [comment]
Sup @Soarc, is there any good news about the fix?
Or is there any kind of workaround i can do to solve it?

**Comment by adamkleingit** [comment]
Also need to overwrite `.getBoundingClientRect().height` in both `lib/directives/tree-animate-open.directive.ts` and `lib/models/tree-virtual-scroll.model.ts`

**Comment by JohnGalt1717** [comment]
Where are we with this? Does 5.0.0 fix this and not call the DOM directly?

**Comment by adamkleingit** [comment]
@JohnGalt1717 @IgorMoreira @Soarc 
Fixed in 5.2.1 - can you verify?
