### ISSUE TITLE
(void 0) is not a function" using webpack

### ISSUE THREAD

**Issue by sadplace** [500tech/angular-tree-component#331]
Hi,
I am using Angular4 and upgraded to the latest version of the tree and i get this error "(void 0) is not a function"
Tree version 3.4.0 works fine but all above that i got this error.
Angular 4 starts on which tree version

I dont know what more information i can give..

Sorry and thanks

**Comment by sadplace** [comment]
i just update all dependencies and i still get this error

UnitHierarchy.html:4 ERROR TypeError: (void 0) is not a function
    at new e (eval at <anonymous> (http://localhost:3000/app.js:1745:2), <anonymous>:5:4410)
    at new e (eval at <anonymous> (http://localhost:3000/app.js:1745:2), <anonymous>:5:16679)
    at createClass (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:11029:26)
    at _createProviderInstance (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:11002:26)
    at createProviderInstance (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:10836:64)
    at createViewNodes (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:12281:49)
    at callViewAction (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:12735:13)
    at execComponentViewsAction (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:12644:13)
    at createViewNodes (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:12318:5)
    at createEmbeddedView (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:12174:5)
    at callWithDebugContext (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:13567:42)
    at Object.debugCreateEmbeddedView [as createEmbeddedView] (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:12913:12)
    at TemplateRef_.createEmbeddedView (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:10378:38)
    at ViewContainerRef_.createEmbeddedView (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:10161:52)
    at UnitView.ngOnInit (eval at <anonymous> (http://localhost:3000/app.js:1661:2), <anonymous>:60:34)
    at checkAndUpdateDirectiveInline (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:10955:19)
    at checkAndUpdateNodeInline (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:12443:17)
    at checkAndUpdateNode (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:12382:16)
    at debugCheckAndUpdateNode (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:13241:59)
    at debugCheckDirectivesFn (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:13182:13)
    at Object.eval [as updateDirectives] (ng:///OrganizationModule/UnitView_Host.ngfactory.js:11:5)
    at Object.debugUpdateDirectives [as updateDirectives] (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:13167:21)
    at checkAndUpdateView (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:12349:14)
    at callViewAction (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:12712:21)
    at execEmbeddedViewsAction (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:12670:17)
    at checkAndUpdateView (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:12350:5)
    at callViewAction (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:12712:21)
    at execComponentViewsAction (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:12644:13)
    at checkAndUpdateView (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:12355:5)
    at callWithDebugContext (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:13567:42)
    at Object.debugCheckAndUpdateView [as checkAndUpdateView] (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:13107:12)
    at ViewRef_.detectChanges (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:10288:18)
    at eval (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:4897:63)
    at Array.forEach (native)
    at ApplicationRef_.tick (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:4897:25)
    at eval (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:4775:106)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:3000/polyfills.js:2794:2), <anonymous>:391:26)
    at Object.onInvoke (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:3965:37)
    at ZoneDelegate.invoke (eval at <anonymous> (http://localhost:3000/polyfills.js:2794:2), <anonymous>:390:32)
    at Zone.run (eval at <anonymous> (http://localhost:3000/polyfills.js:2794:2), <anonymous>:141:43)
    at NgZone.run (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:3833:62)
    at Object.next (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:4775:82)
    at SafeSubscriber.schedulerFn [as _next] (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:3667:52)
    at SafeSubscriber.__tryOrUnsub (eval at <anonymous> (http://localhost:3000/vendor.js:124:2), <anonymous>:238:16)
    at SafeSubscriber.next (eval at <anonymous> (http://localhost:3000/vendor.js:124:2), <anonymous>:185:22)
    at Subscriber._next (eval at <anonymous> (http://localhost:3000/vendor.js:124:2), <anonymous>:125:26)
    at Subscriber.next (eval at <anonymous> (http://localhost:3000/vendor.js:124:2), <anonymous>:89:18)
    at EventEmitter.Subject.next (eval at <anonymous> (http://localhost:3000/vendor.js:286:2), <anonymous>:55:25)
    at EventEmitter.emit (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:3653:76)
    at NgZone.checkStable (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:3930:40)
    at NgZone.setHasMicrotask (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:4014:14)
    at Object.onHasTask (eval at <anonymous> (http://localhost:3000/vendor.js:100:2), <anonymous>:3977:31)
    at ZoneDelegate.hasTask (eval at <anonymous> (http://localhost:3000/polyfills.js:2794:2), <anonymous>:444:37)
    at ZoneDelegate._updateTaskCount (eval at <anonymous> (http://localhost:3000/polyfills.js:2794:2), <anonymous>:464:22)
    at Zone._updateTaskCount (eval at <anonymous> (http://localhost:3000/polyfills.js:2794:2), <anonymous>:288:34)
    at Zone.runTask (eval at <anonymous> (http://localhost:3000/polyfills.js:2794:2), <anonymous>:208:30)
    at drainMicroTaskQueue (eval at <anonymous> (http://localhost:3000/polyfills.js:2794:2), <anonymous>:584:35)
    at HTMLFormElement.ZoneTask.invoke (eval at <anonymous> (http://localhost:3000/polyfills.js:2794:2), <anonymous>:490:25)

**Comment by psilospore** [comment]
I'm getting the same error with angular 2.3.1 and webpack 1.13.2

**Comment by psilospore** [comment]
Works when I use angular-tree-component 3.2.3

**Comment by roni-frantchi** [comment]
Like those above, I'm getting the same thing here. Any version > 3.2.3 fails with `(void 0) is not a function`.

...That's on SystemJS though.
That said, I've seen you've since decided to stop supporting SystemJS entirely.
I don't think a library should dictate what kind of bundler (SystemJS does have one too), should a project have.  Especially one that had been the go to for the Angular team just a year back (and still remains for many seed projects).  

Nevertheless, I'm not looking to complain but instead I would love to know what were the issues and see if I can help fix them, given a proper issue describing what fails were to open.  
Still, more than anything I resent a condescending comment such as:
> _*Modern*_ web applications use bundlers like Webpack.

**Comment by adamkleingit** [comment]
@roni-frantchi, sorry if that felt condenscending - and you are completely right. Every technology choice is per requirements and project. I decided to stop supporting it because it brings too many issues, and I saw many other packages are dropping support.
However, I still want to keep encouraging people to use webpack. But again - I was wrong the way I wrote it.

**Comment by adamkleingit** [comment]
@sadplace, @psilospore  can you share your config files ?
package.json, angular-cli.json, webpack.config.js

Thanks

**Comment by roni-frantchi** [comment]
@adamkleingit I apologize if I had come on to strong. I do appreciate your reply. 
My sincere thanks for a great library.
I'll post in this thread if I'll be able to figure out the `(void 0) is not a function` I got when using System.
Maybe it'll remedy the Webpack issue seen here as well.

**Comment by colinbate** [comment]
I'm seeing this too and it looks like it would affect anyone using the UMD bundle. Since 3.4.1, the UMD bundle contains a function invocation on `(void 0)`. There are two of them in the most recent code. They originate in `lib/models/tree-options.model.ts` through the use of the two `lodash` methods: `defaultsDeep` and `omit`. Unlike other files using `lodash`, this one doesn't to a destructuring, it just references the functions from the underscore identifier directly. It seems like the Rollup uglify step is probably over optimizing.

**Comment by colinbate** [comment]
So the issue was fixed for me by adding the dependencies to Rollup's `external` list: `mobx`, `mobx-angular`, `lodash`. Is the UMD file maintained?

**Comment by GianlucaMaggio** [comment]
I have the same question. In this case the fix is very simple (adding lodash to rollup.config) and after that it works with system.js. Is it possible to do it?

**Comment by DavidKDeutsch** [comment]
I'll put in a pull request with the changes. FWIW, it would also work if the appropriate lodash methods were added to the rollup config's commonjs plugin, but then lodash would still be bundled in the umd, which is a waste (plus, it is listed as a dependency anyway).

**Comment by jerradpatch** [comment]
I just received this issue using angular-cli, but only for the production build, probably during uglyification.

**Comment by adamkleingit** [comment]
This was a dependency problem - should be fixed in latest version

**Comment by broweratcognitecdotcom** [comment]
I get the same error only when using --prod and only after upgrading to angular version 5. It only happens about 50% of the time. Executing the same command again always fixes the problem. I am not using the tree component that others have mentioned. I am certain it has nothing to do with an external library. Because it would happen 100% of the time. The issue should not have been closed.

**Comment by dizzy721** [comment]
> Uncaught TypeError: (void 0) is not a function
>     at Object.cDNt (main.2d2b3f0de20dee881539.bundle.js:1)
>     at o (inline.a443620b1a7e83c745b9.bundle.js:1)
>     at Object.0 (main.2d2b3f0de20dee881539.bundle.js:1)
>     at o (inline.a443620b1a7e83c745b9.bundle.js:1)
>     at window.webpackJsonp (inline.a443620b1a7e83c745b9.bundle.js:1)
>     at main.2d2b3f0de20dee881539.bundle.js:1
> cDNt @ main.2d2b3f0de20dee881539.bundle.js:1
> o @ inline.a443620b1a7e83c745b9.bundle.js:1
> 0 @ main.2d2b3f0de20dee881539.bundle.js:1
> o @ inline.a443620b1a7e83c745b9.bundle.js:1
> window.webpackJsonp @ inline.a443620b1a7e83c745b9.bundle.js:1
> (anonymous) @ main.2d2b3f0de20dee881539.bundle.js:1

 

This is the error I'm seeing on 1.6.3 of the CLI and 5.1.3 of Angular. I am running `ng serve --prod --build-optimizer=true --env=dev`. It works fine at first but throws this error when rebuilding after changes. Currently working around it by just reloading the command when I need it, but it was working fine until recently. Error is thrown every time I connect to the dev server.

**Comment by thariesl** [comment]
@broweratcognitecdotcom yep still happening with --prod, good thing this is closed right?

**Comment by MiraYuan** [comment]
my project work well when ng s --prod, but cannot work well and error happen"(void 0) is not a function" when it is used in a websphere project... 
why? why? why? help~~~
